name: Label issues 
on:
  issues:
    types:
      - reopened 
      - opened
jobs:
  label_issues: # name of the job
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-triage"]
            })
     - uses: wow-actions/auto-comment@v1
        with:
          issuesOpenedReactions: 'New Issue, +1'
          issuesOpenedComment: |
            👋 @{{ author }}
            New Issue is re-opened.The Dev team will get back.