name: Label issues 
on:
  issues:
    types:
      - reopened 
      - opened
jobs:
  label_issues: 
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
      - uses: wow-actions/auto-comment@v1   
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-triage"]
            })
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'New Issue, +1'
          issuesOpenedComment: |
            New Issue is re-opened.The Dev team will get back.